using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Eventbox.Ticketing.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ChangeTicketTypeIdToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(name: "FK_PricingPhaseAvailability_TicketTypeAvailability_TicketTypeA~", table: "PricingPhaseAvailability");

            migrationBuilder.Sql("ALTER TABLE \"TicketTypeAvailability\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"TicketTypeAvailability\" ALTER COLUMN \"Id\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.Sql("ALTER TABLE \"Tickets\" ALTER COLUMN \"TicketTypeId\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"Tickets\" ALTER COLUMN \"TicketTypeId\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"Id\" TYPE uuid USING gen_random_uuid();");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"TicketTypeAvailabilityId\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"TicketTypeAvailabilityId\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"TicketTypeId\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"TicketTypeId\" TYPE uuid USING gen_random_uuid();");
            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"PricingPhaseId\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"PricingPhaseId\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.AddForeignKey(
                name: "FK_PricingPhaseAvailability_TicketTypeAvailability_TicketTypeA~",
                table: "PricingPhaseAvailability",
                column: "TicketTypeAvailabilityId",
                principalTable: "TicketTypeAvailability",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(name: "FK_PricingPhaseAvailability_TicketTypeAvailability_TicketTypeA~", table: "PricingPhaseAvailability");

            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"TicketTypeAvailabilityId\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"Id\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhaseAvailability\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql("ALTER TABLE \"TicketTypeAvailability\" ALTER COLUMN \"Id\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"TicketTypeAvailability\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql("ALTER TABLE \"Tickets\" ALTER COLUMN \"TicketTypeId\" TYPE integer USING 0;");

            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"TicketTypeId\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"OrderItems\" ALTER COLUMN \"PricingPhaseId\" TYPE integer USING 0;");

            migrationBuilder.AddForeignKey(
                name: "FK_PricingPhaseAvailability_TicketTypeAvailability_TicketTypeA~",
                table: "PricingPhaseAvailability",
                column: "TicketTypeAvailabilityId",
                principalTable: "TicketTypeAvailability",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
