services:
  yarp.api.gateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Auth/Auth.API/Dockerfile

  event.api:
    image: ${DOCKER_REGISTRY-}eventapi
    build:
      context: .
      dockerfile: EventManagement/Event.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Payment/Payment.API/Dockerfile

  ticketing.api:
    image: ${DOCKER_REGISTRY-}ticketingapi
    build:
      context: .
      dockerfile: Ticketing/Ticketing.API/Dockerfile

  eventdb:
    image: postgres:16

  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Notification/Notification.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management

  mailhog:
    image: mailhog/mailhog
