services:
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Auth/Auth.API/Dockerfile

  event.api:
    image: ${DOCKER_REGISTRY-}eventapi
    build:
      context: .
      dockerfile: EventManagement/Event.API/Dockerfile

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Payment/Payment.API/Dockerfile

  Ticketingapi:
    image: ${DOCKER_REGISTRY-}registrationapi
    build:
      context: .
      dockerfile: Registration/TicketingAPI/Dockerfile

  eventdb:
    image: postgres:16

  rabbitmq:
    image: rabbitmq:3-management
