using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Eventbox.EventManagement.EventApi.Migrations
{
    /// <inheritdoc />
    public partial class ChangeTicketTypeIdToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(name: "FK_PricingPhase_TicketType_TicketTypeId", table: "PricingPhase");

            migrationBuilder.Sql("ALTER TABLE \"TicketType\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"TicketType\" ALTER COLUMN \"Id\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"Id\" TYPE uuid USING gen_random_uuid();");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"TicketTypeId\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"TicketTypeId\" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.AddForeignKey(
                name: "FK_PricingPhase_TicketType_TicketTypeId",
                table: "PricingPhase",
                column: "TicketTypeId",
                principalTable: "TicketType",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(name: "FK_PricingPhase_TicketType_TicketTypeId", table: "PricingPhase");

            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"TicketTypeId\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"Id\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"PricingPhase\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.Sql("ALTER TABLE \"TicketType\" ALTER COLUMN \"Id\" TYPE integer USING 0;");
            migrationBuilder.Sql("ALTER TABLE \"TicketType\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddForeignKey(
                name: "FK_PricingPhase_TicketType_TicketTypeId",
                table: "PricingPhase",
                column: "TicketTypeId",
                principalTable: "TicketType",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
