<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Eventbox.Payment.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventBus\EventBus.Core\EventBus.Core.csproj" />
    <ProjectReference Include="..\..\Shared\Eventbox.Contracts\Eventbox.Contracts.csproj" />
    <ProjectReference Include="..\Payment.Core\Payment.Core.csproj" />
  </ItemGroup>

</Project>
