<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Eventbox.Ticketing.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventBus\EventBus.Core\EventBus.Core.csproj" />
    <ProjectReference Include="..\..\Shared\Eventbox.Contracts\Eventbox.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Eventbox.Shared\Eventbox.Shared.csproj" />
    <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
  </ItemGroup>

</Project>
