<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventManagement\Event.API\Event.API.csproj" />
    <ProjectReference Include="..\..\Payment\Payment.Core\Payment.Core.csproj" />
    <ProjectReference Include="..\..\Ticketing\Ticketing.Application\Ticketing.Application.csproj" />
    <ProjectReference Include="..\..\Ticketing\Ticketing.Domain\Ticketing.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Eventbox.Shared\Eventbox.Shared.csproj" />
  </ItemGroup>

</Project>
